batch_size: 1
body_model:
  model_type: smplx
  num_pca_comps: 12
contact:
  euclidean_thres: 0.03
  geodesic_thres: 0.3
  test_segments: True
loss:
  contact_weight: 30
  inside_weight: 30
  outside_weight: 0.01
  hand_contact_prior_weight: 1.0
  pose_prior_weight: 1.0 
  hand_pose_prior_weight: 0.01
  angle_weight: 0.001
optimizer:
  name: adam
  learning_rate_body: 0.01
  learning_rate_hands: 0.01
  max_iters: 500